language: go
sudo: false
go_import_path: github.com/gobeam/custom-validator
go:
- 1.9

env:
  - GO111MODULE=on

before_install:
- go mod download

script:
- go test

after_success:
- bash <(curl -s https://codecov.io/bash)
