language: c
os:
  - linux
  - osx
dist: trusty
sudo: false
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=master bash)"
script:
  - go build
  - go test
after_success:
  - bash <(curl -s https://codecov.io/bash)